version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/reverb-client/src:/app/src
      - ./frontend/reverb-client/public:/app/public

  backend:
    build: ./backend
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data: