name: spotify-music-app
region: nyc

# Database
databases:
  - name: reverb-db
    engine: MYSQL
    production: true

# Backend API
services:
  - name: backend
    github:
      repo: 21vincentchu/spotify-music-app
      branch: reverb-production
      deploy_on_push: true
    dockerfile_path: backend/Dockerfile
    http_port: 5000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: FLASK_ENV
        value: production
      - key: SPOTIFY_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: SPOTIFY_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPOTIPY_REDIRECT_URI
        value: ${backend.PUBLIC_URL}/callback
      - key: MYSQL_HOST
        value: ${reverb-db.HOSTNAME}
      - key: MYSQL_PORT
        value: ${reverb-db.PORT}
      - key: MYSQL_USER
        value: ${reverb-db.USERNAME}
      - key: MYSQL_PASSWORD
        value: ${reverb-db.PASSWORD}
      - key: MYSQL_DATABASE
        value: defaultdb
