name: spotify-music-app
region: nyc

# Database - add this later when ready
# databases:
#   - name: spotify-db
#     engine: MYSQL
#     version: "8"
#     production: true
#     cluster_name: spotify-db-cluster

# Backend API
services:
  - name: backend
    github:
      repo: 21vincentchu/spotify-music-app
      branch: backend-vinny
      deploy_on_push: true
    dockerfile_path: backend/Dockerfile
    http_port: 5000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: FLASK_ENV
        value: production
      - key: SPOTIFY_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: SPOTIFY_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPOTIPY_REDIRECT_URI
        value: ${backend.PUBLIC_URL}/callback
      # Database env vars - add when database is created
      # - key: DATABASE_URL
      #   value: ${spotify-db.DATABASE_URL}
      # - key: MYSQL_HOST
      #   value: ${spotify-db.HOSTNAME}
      # - key: MYSQL_PORT
      #   value: ${spotify-db.PORT}
      # - key: MYSQL_USER
      #   value: ${spotify-db.USERNAME}
      # - key: MYSQL_PASSWORD
      #   value: ${spotify-db.PASSWORD}
      # - key: MYSQL_DATABASE
      #   value: ${spotify-db.DATABASE}

# Frontend
  - name: frontend
    github:
      repo: 21vincentchu/spotify-music-app
      branch: backend-vinny
      deploy_on_push: true
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        value: ${backend.PUBLIC_URL}
